### ISSUE TITLE
설정 파일 읽기 기능 개발

### ISSUE THREAD

**Issue by 4whomtbts** [DGU-AILab/Plannel#3]
아래와 같은 property를 갖고 있는 ini 형식파일을 읽는 기능 추가 

version=1
bootstrap.server=localhost:8081
heartbeat.interval.ms=1000

====
파이썬에서   에시 => [ 코드 # 결과 ]
print(VERSION) # 1
print(BOOTSTRAP_SERVER) # localhost:8081
print(HEARTBEAT_INTERVAL_MS) # 1000

**Comment by RieLCho** [comment]
https://github.com/DGU-AILab/Plannel/pull/5

ini 파일은 처음 다뤄보는데 한번 확인해주세요.
감사합니다.

**Comment by 4whomtbts** [comment]
확인했습니다!
